const feeders={FENAKA:[],SS01:[],SS02:['Maza','Hiyaalee','Keveli','Sunset','Meylaa','Tharividhaage'],SS03:[],SS04:[],SS05:[],SS06:[],SS07:[]};
const states=JSON.parse(localStorage.getItem('fenakaStates')||'{}');let current=null;
const houses=document.querySelector('#houses'),selected=document.querySelector('#selected'),search=document.querySelector('#search'),suggestions=document.querySelector('#suggestions');
const viewport=document.querySelector('#mapViewport'),stage=document.querySelector('#mapStage'),highlight=document.querySelector('#houseHighlight');let scale=1,tx=0,ty=0;
function applyTransform(){stage.style.transform=`translate(${tx}px,${ty}px) scale(${scale})`}
function resetMap(){scale=1;tx=0;ty=0;highlight.hidden=true;applyTransform()}
function findLabel(name){const n=name.trim().toLowerCase();return mapLabels.find(x=>x.name.toLowerCase()===n)||mapLabels.find(x=>x.name.toLowerCase().includes(n))}
function zoomToHouse(name){const p=findLabel(name);if(!p)return;highlight.style.left=p.x+'%';highlight.style.top=p.y+'%';highlight.hidden=false;scale=5;const vw=viewport.clientWidth,vh=viewport.clientHeight;tx=vw/2-(p.x/100)*stage.offsetWidth*scale;ty=vh/2-(p.y/100)*stage.offsetHeight*scale;applyTransform();setTimeout(()=>highlight.classList.add('pulse'),10)}
function render(){let list=current?feeders[current]:Object.values(feeders).flat();let q=search.value.trim().toLowerCase();list=[...new Set(list)].filter(x=>x.toLowerCase().includes(q));houses.innerHTML=list.length?'':'<p class="hint">No houses assigned yet.</p>';for(const name of list){let row=document.createElement('button');row.className='house';let st=states[name]||'green';row.innerHTML=`<span>${name}</span><span class="status ${st}"></span>`;row.onclick=()=>zoomToHouse(name);row.querySelector('.status').onclick=e=>{e.stopPropagation();states[name]=st==='green'?'red':'green';localStorage.setItem('fenakaStates',JSON.stringify(states));render()};houses.appendChild(row)}}
function showSuggestions(){const q=search.value.trim().toLowerCase();if(q.length<2){suggestions.style.display='none';return}const seen=new Set(),matches=[];for(const x of mapLabels){const n=x.name.trim();if(n.length<2||seen.has(n.toLowerCase()))continue;if(n.toLowerCase().includes(q)){seen.add(n.toLowerCase());matches.push(n);if(matches.length>=12)break}}suggestions.innerHTML=matches.map(n=>`<button>${n}</button>`).join('');suggestions.style.display=matches.length?'block':'none';[...suggestions.children].forEach((b,i)=>b.onclick=()=>{search.value=matches[i];suggestions.style.display='none';zoomToHouse(matches[i]);render()})}
document.querySelectorAll('[data-feeder]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-feeder]').forEach(x=>x.classList.remove('active'));b.classList.add('active');current=b.dataset.feeder;selected.textContent=current==='FENAKA'?'Fenaka Corporation Fonadhoo Branch Feeder':current.replace('SS','SS ');render()});
search.oninput=()=>{showSuggestions();render()};search.onkeydown=e=>{if(e.key==='Enter'){const m=findLabel(search.value);if(m){zoomToHouse(m.name);suggestions.style.display='none'}}};
document.querySelector('#zoomIn').onclick=()=>{scale=Math.min(8,scale*1.35);applyTransform()};document.querySelector('#zoomOut').onclick=()=>{scale=Math.max(.6,scale/1.35);applyTransform()};document.querySelector('#resetMap').onclick=resetMap;
document.querySelector('#adminBtn').onclick=()=>document.querySelector('#dlg').showModal();render();
